LLM:
  model: 'qwen-plus-latest'
  # temperature: 0 #  0 0.7
  # top_p: 1 # 0 0.95
  # frequency_penalty = 0  # 增大惩罚以减少重复的高频词
  # presence_penalty = 0  # 增大惩罚以减少已经提到过的概念
  response_format: {"type": "json_object"}

system_prompt: |
  You are a log-based software system anomaly detection assistant, and you need to determine if there is an anomaly based on a sequence of logs that I give you while the system is running.

cot_prompt: |
  You will be given a window of {file_system} logs separated by newlines. Based on the current window of logs, determine whether the system is currently in an [Abnormal] state or [Normal] state. Your response should be in the specified JSON format.

  # Notes:
  The system itself has a certain degree of fault tolerance, so even though some logs may contain warning messages, it does not necessarily mean that the system is in an [Abnormal] state.

  # The window of log sequence that requires your anomaly detection is:
      {logs}

  # And You should output the result in the following JSON format:
  {{
    "system_state": "Normal or Abnormal",
    "reason": "A brief explanation of why you classified the system state as [Normal] or [Abnormal]."
  }}

  Please analyze the logs, explain your reasoning, and then conclude with either "system_state": "Normal" or "system_state": "Abnormal"


our_prompt: |
  You will be given a window of {file_system} logs separated by newlines. Based on the current window of logs, determine whether the system is currently in an [Abnormal] state or [Normal] state. Your response should be in the specified JSON format.

  # Notes:
  1. The system has a certain degree of fault tolerance, so warning messages alone do not necessarily indicate an [Abnormal] state.
  2. You are also given Top-k similar logs obtained using embeddings trained via contrastive learning on a large training set. 
  3. Note that the embeddings might be unreliable in certain cases, so focus on your own analysis of the current logs rather than relying solely on these references.

  # The window of log sequence that requires your anomaly detection is:
      {logs}

  # The Top-k similar logs and their similarity scores are provided below:
      {top_k_logs}

  # Output the result in the following JSON format:
  {{
    "system_state": "Normal or Abnormal",
    "reason": "A brief explanation of why you classified the system state as [Normal] or [Abnormal]."
  }}

  Please analyze the logs, prioritize your own judgment, and conclude with either "system_state": "Normal" or "system_state": "Abnormal".
