dataset_name: BGL
dataset_dir: dataset
structured_log_path: ../LogCAE/dataset/example/BGL/BGL_2k.log_structured.csv
bert_model: bert-base-uncased
cache_dir: ./cache_dir/

result_dir: ./results/clslog/bgl_demo/

split_method: sequential
train_ratio: 0.8
gap_days: 0
sample_size: null

window_size: 5
step_size: 5
embedding_method: mean
emb_batch_size: 32

use_hdbscan: false
min_cluster_size: 3
min_samples: 1

k: 3
confidence_threshold: 0.9

use_siamese_network: true
cl_num_epochs: 2
batch_size: 64
eval_in_train: false

use_large_model: false
use_cache: false
wandb_mode: disabled

LLM:
  model: qwen-plus
  temperature: 0.01
  top_p: 0.95
